/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_lms;
import java.util.Date;
import controle.connetion.modele.ModeleAdherents;
import controle.connetion.modele.ModeleBooks;
import controle.connetion.controle.utilitaire.GestionDates;
import entite.Transaction;
import entite.adherents;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Princy-Grace
 */

public class Gestion_Abonnes extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_Abonnes
     */
   
    public Gestion_Abonnes() {
      
        initComponents();
        setLocationRelativeTo(null);
    }

    public JButton getjButton4() {
        return jButton4;
    }

    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }
    
    public JTextField getjTxT_Matricule() {
        return jTxT_Matricule;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTxT_Rech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCmb_rech = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(leModeleAdherent);
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTxT_Date_naissance = new javax.swing.JTextField();
        panel2 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxt_Statut = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxT_nom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxT_phone_number = new javax.swing.JTextField();
        jTxT_sexe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxT_Matricule = new javax.swing.JTextField();
        jTxT_Login = new javax.swing.JTextField();
        jTxt_Id_User = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxT_nationalite = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxT_Adresse_mail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxT_Password = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Deconexion = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTxT_Rech.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/find_user_male_96px_1.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCmb_rech.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCmb_rech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nom", "sexe", "matricule", "id_user", "login", "nationalite", "statut" }));

        jPanel3.setBackground(new java.awt.Color(57, 105, 138));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVNUE SUR LMS");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 215, -1));

        jPanel5.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1332, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Liste des Abonnés de la bibliothèque");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 262, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/books_35px.png"))); // NOI18N
        jButton10.setText("Gestion d'articles");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/data_transfer_30px.png"))); // NOI18N
        jButton12.setText("Gestion d'emprunts");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/combo_chart_30px.png"))); // NOI18N
        jButton13.setText("Statistiques LMS");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setBackground(new java.awt.Color(204, 102, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/cool.png"))); // NOI18N

        jLabel17.setBackground(new java.awt.Color(204, 102, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("LOGICIEL DE GESTION LMS");

        jLabel18.setBackground(new java.awt.Color(204, 102, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Université Inter-Etats Congo Cameroun");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBackground(new java.awt.Color(57, 105, 138));

        jLabel9.setBackground(new java.awt.Color(204, 102, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GESTION D'ABONNES");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/add_user_male_skin_type_7_30px.png"))); // NOI18N
        jButton6.setText("Ajouter Abonné");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/denied_30px.png"))); // NOI18N
        jButton2.setText("Suprimer Abonné");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/todo_list_35px.png"))); // NOI18N
        jButton9.setText("Tout selectionner");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/refresh_30px.png"))); // NOI18N
        jButton3.setText("Actualiser");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
        );

        jPanel1.setBackground(new java.awt.Color(57, 105, 138));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxT_Date_naissance.setEditable(false);
        jPanel1.add(jTxT_Date_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 84, 220, -1));

        panel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FICHE Abonné");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/edit_property_25px.png"))); // NOI18N
        jButton7.setText("Modifier fiche");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date de naissance");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 54, -1, -1));

        jTxt_Statut.setEditable(false);
        jPanel1.add(jTxt_Statut, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 135, 220, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Statut");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 118, -1, -1));

        jTxT_nom.setEditable(false);
        jPanel1.add(jTxT_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 192, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nom (s) :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, -1, -1));

        jTxT_phone_number.setEditable(false);
        jPanel1.add(jTxT_phone_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 299, 140, -1));

        jTxT_sexe.setEditable(false);
        jPanel1.add(jTxT_sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sexe");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 226, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Matricule");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 175, -1, -1));

        jTxT_Matricule.setEditable(false);
        jPanel1.add(jTxT_Matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 192, 180, -1));

        jTxT_Login.setEditable(false);
        jPanel1.add(jTxT_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 299, 180, -1));

        jTxt_Id_User.setEditable(false);
        jPanel1.add(jTxt_Id_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 243, 180, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Id_user");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 226, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/save_25px.png"))); // NOI18N
        jButton4.setText("Enregistrer les modifications");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 451, -1, 31));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RessourcesIcones/circled_user_male_skin_type_6_96px.png"))); // NOI18N
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, 104, 109));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Login");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 283, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numéro de Tel");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 283, -1, -1));

        jTxT_nationalite.setEditable(false);
        jPanel1.add(jTxT_nationalite, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 349, 180, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nationalite");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 333, -1, -1));

        jTxT_Adresse_mail.setEditable(false);
        jPanel1.add(jTxT_Adresse_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 349, 140, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Adresse");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 333, -1, -1));

        jTxT_Password.setEditable(false);
        jPanel1.add(jTxT_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 180, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Mot de passe");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 383, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1374, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addGap(17, 17, 17)
                        .addComponent(jCmb_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxT_Rech, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmb_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxT_Rech, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18))
                                .addComponent(jLabel6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        jMenuBar1.setMinimumSize(new java.awt.Dimension(203, 32769));

        jMenu1.setText("Mon Profil");

        Deconexion.setText("Deconexion...");
        Deconexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeconexionMouseClicked(evt);
            }
        });
        Deconexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconexionActionPerformed(evt);
            }
        });
        jMenu1.add(Deconexion);

        jMenuItem2.setText("Modifier compte");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Paramètres du logiciel");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("?");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeconexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeconexionMouseClicked

    }//GEN-LAST:event_DeconexionMouseClicked

    private void DeconexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconexionActionPerformed
        System.out.println("Deconnxion en cours...");
        System.exit(0);

    }//GEN-LAST:event_DeconexionActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked

    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
           Gestion_articles g = new Gestion_articles();
             g.setVisible(true);
             dispose();
             g.jBtn_enrg.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        EnregistrementAbonnes l_EnregistrementAbonnées = new EnregistrementAbonnes(leModeleAdherent);
        l_EnregistrementAbonnées.setVisible(true);
       
        //l_EnregistrementAbonnées.getjTxT_Time().requestFocus(true);
        Date dtDate = new Date();
        String strDate = GestionDates.dateEnChaineFR(dtDate);
        l_EnregistrementAbonnées.getjTxt_DateNaissance().setText(strDate);
        l_EnregistrementAbonnées.getjTxt_DateNaissance().setEditable(true);
        l_EnregistrementAbonnées.setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        EmpruntArticles l_EmpruntArticles = new EmpruntArticles(leModelebooks);
        l_EmpruntArticles.setVisible(true);
         Date dtDate = new Date();
        String strDate = GestionDates.dateEnChaineFR(dtDate);
        l_EmpruntArticles.getjTxt_Date_emprunt().setText(strDate);
         l_EmpruntArticles.getjTxt_Date_remise().setText(strDate);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // Gestion du simple clic 
        int NumLigne;
        NumLigne = jTable1.getSelectedRow();
        jTxT_nom.setText(String.valueOf(jTable1.getValueAt(NumLigne, 0)));
        jTxT_sexe.setText(String.valueOf(jTable1.getValueAt(NumLigne, 1)));
        jTxT_phone_number.setText(String.valueOf(jTable1.getValueAt(NumLigne, 2)));
        jTxT_Adresse_mail.setText(String.valueOf(jTable1.getValueAt(NumLigne, 3)));
        jTxT_Date_naissance.setText(String.valueOf(jTable1.getValueAt(NumLigne, 4)));
        jTxt_Statut.setText(String.valueOf(jTable1.getValueAt(NumLigne, 5)));
        jTxT_Matricule.setText(String.valueOf(jTable1.getValueAt(NumLigne, 6)));
        jTxt_Id_User.setText(String.valueOf(jTable1.getValueAt(NumLigne, 9)));
        jTxT_Login.setText(String.valueOf(jTable1.getValueAt(NumLigne, 7)));
        jTxT_Password.setText(String.valueOf(jTable1.getValueAt(NumLigne, 8)));
        jTxT_nationalite.setText(String.valueOf(jTable1.getValueAt(NumLigne, 10)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       int numLigne = jTable1.getSelectedRow();
       if (numLigne == -1) {
           JOptionPane.showMessageDialog(null, "Vous devez selectionnez " + "une ligne pour la supprimer", "Avertissement", JOptionPane.WARNING_MESSAGE);
           
       }else{
           int valid = JOptionPane.showConfirmDialog(null, "Êtes-vous sur de vouloir supprimer" + " l'adherent selectionner ?"
				, "Supprimer", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
               if (valid == 0 ){
                   String matricule = jTable1.getValueAt(numLigne, 6).toString();
                   adherents unAdherent = new adherents(matricule);
                   unAdherent.supprimerCRUD(matricule);
                   leModeleAdherent.supprimerMOD(numLigne);
               }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTable1.revalidate();
        jTable1.repaint();
        Gestion_Abonnes g = new Gestion_Abonnes();
        dispose();
        g.setVisible(true);
        g.jButton4.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      
       
       
    //  if ()  
         int numLigne = jTable1.getSelectedRow();
        String matriculej = jTxT_Matricule.getText();
        if (!matriculej.equals("")){
             String nomj = jTxT_nom.getText();
              String sexej = jTxT_sexe.getText();
               int phone_numberj =Integer.valueOf(jTxT_phone_number.getText()) ;
               String adresse_mailj = jTxT_Adresse_mail.getText();
        String strDate = jTxT_Date_naissance.getText() ;
        String statutj = jTxt_Statut.getText();
         int id_userj = Integer.valueOf(jTxt_Id_User.getText());
        String loginj = jTxT_Login.getText();
        String passwordj = jTxT_Password.getText();
        String nationalitej = jTxT_nationalite.getText();
             String strmysql = GestionDates.chaineDateFRversEN(strDate);
         Date dtDate = new Date();
            dtDate = GestionDates.dateJavaEnDateSQL(dtDate);
        adherents unadherent = new adherents(nomj, sexej, phone_numberj, adresse_mailj, statutj, matriculej, loginj, passwordj, nationalitej, dtDate, id_userj);
            //strDate = GestionDates.chaineDateFRversEN(strDate);
    boolean bCreation = false;
    bCreation = unadherent.modifierCRUD(nomj, sexej, phone_numberj, adresse_mailj, statutj, matriculej, loginj, passwordj, nationalitej, strDate, id_userj);
    if (bCreation) {
        leModeleAdherent.setValueAt(nomj, numLigne, 0);
        leModeleAdherent.setValueAt(sexej, numLigne, 1);
        leModeleAdherent.setValueAt(phone_numberj, numLigne, 2);
        leModeleAdherent.setValueAt(adresse_mailj, numLigne, 3);
        leModeleAdherent.setValueAt(strDate, numLigne, 4);
        leModeleAdherent.setValueAt(statutj, numLigne, 5);
        leModeleAdherent.setValueAt(matriculej, numLigne, 6);
        leModeleAdherent.setValueAt(loginj , numLigne, 7);
        leModeleAdherent.setValueAt(passwordj , numLigne, 8);
        leModeleAdherent.setValueAt(id_userj, numLigne, 9);
        leModeleAdherent.setValueAt(nationalitej, numLigne, 10);
       leModeleAdherent.modifieMOD(numLigne, numLigne, unadherent);
        jTxT_Matricule.setEditable(false); 
          jTxT_Adresse_mail.setEditable(false); 
          jTxT_phone_number.setEditable(false); 
          jTxT_nom.setEditable(false); 
          jTxT_sexe.setEditable(false); 
          jTxt_Id_User.setEditable(false); 
          jTxt_Statut.setEditable(false); 
          jTxT_Login.setEditable(false); 
          jTxT_Password.setEditable(false); 
          jTxT_nationalite.setEditable(false); 
          jTxT_Date_naissance.setEditable(false); 
                jButton4.setVisible(false);
    }
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         int numLigne = jTable1.getSelectedRow();
         
       if (numLigne == -1) {
           JOptionPane.showMessageDialog(null, "Vous devez selectionnez " + "une ligne pour la modifier", "Avertissement", JOptionPane.WARNING_MESSAGE);
          
       }else{
          JOptionPane.showMessageDialog(null, "Vous pouvez modifier les informations ");
          jTxT_Matricule.setEditable(true); 
          jTxT_Adresse_mail.setEditable(true); 
          jTxT_phone_number.setEditable(true); 
          jTxT_nom.setEditable(true); 
          jTxT_sexe.setEditable(true); 
          jTxt_Id_User.setEditable(true); 
          jTxt_Statut.setEditable(true); 
          jTxT_Login.setEditable(true); 
          jTxT_Password.setEditable(true); 
          jTxT_nationalite.setEditable(true); 
          jTxT_Date_naissance.setEditable(true); 
             jButton4.setVisible(true);
            
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                String matriculej = jTxT_Rech.getText();
                String cmb = jCmb_rech.getSelectedItem().toString();
        entite.adherents l_adherent = new entite.adherents(matriculej);
        ArrayList<adherents> nouvelleListe = 
                l_adherent.chercherCRUD(cmb,matriculej);
        leModeleAdherent.lireRecupMOD(nouvelleListe);
         jTable1.revalidate();
        jTable1.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       
        
        Statistiques l_Statistiques = new Statistiques();
       l_Statistiques.setVisible(true);
        ModeleAdherents test = new ModeleAdherents();
        int val = test.getRowCount();
        String txt = String.valueOf(val);
        ModeleBooks test1 = new ModeleBooks();
        int val1 = test1.getRowCount();
       
        String txt1 = String.valueOf(val1);
         l_Statistiques.jLbl_article.setText(txt1);
      l_Statistiques.jLbl_adherent.setText(txt);
       Transaction tran = new Transaction();
        try {
            int nb =tran.nombre();
            int nb1  = tran.nombre1();
           String text = String.valueOf(nb);
            String text1 = String.valueOf(nb1);
            l_Statistiques.jLbl_article.setText(text);
          l_Statistiques.getjLbl_emprunt().setText(text1);
        } catch (SQLException ex) {
            Logger.getLogger(Gestion_Abonnes.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButton13ActionPerformed
   // private void prepa?odification(){
      //  int NumLigne = -1;
      //  NumLigne =jTable1.getSelectedRows();
      //  if (NumLigne == -1){
           // JOptionPane.showMessageDialog(null, "Sellectionnez aupavant" + "la liggne à modifier" + '\n'+ "");
      //  }
   // }
    /**
     * @param args the command line arguments
     */
     private ModeleAdherents leModeleAdherent = new ModeleAdherents();
      private ModeleBooks leModelebooks = new ModeleBooks();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Abonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Abonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Abonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Abonnes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Abonnes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Deconexion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jCmb_rech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxT_Adresse_mail;
    private javax.swing.JTextField jTxT_Date_naissance;
    private javax.swing.JTextField jTxT_Login;
    private javax.swing.JTextField jTxT_Matricule;
    private javax.swing.JTextField jTxT_Password;
    private javax.swing.JTextField jTxT_Rech;
    private javax.swing.JTextField jTxT_nationalite;
    private javax.swing.JTextField jTxT_nom;
    private javax.swing.JTextField jTxT_phone_number;
    private javax.swing.JTextField jTxT_sexe;
    private javax.swing.JTextField jTxt_Id_User;
    private javax.swing.JTextField jTxt_Statut;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
