/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_lms;

import javax.swing.JTextField;
import controle.connetion.controle.utilitaire.GestionDates;
import controle.connetion.modele.ModeleBooks;
import entite.Books;
import entite.Transaction;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author lenovo
 */
public class RemisesEmprunt extends javax.swing.JFrame {

    /**
     * Creates new form RemisesEmprunt
     */
    public RemisesEmprunt() {
        initComponents();
          setLocationRelativeTo(null);
    }

    public JTextField getjTxt_codeLivre() {
        return jTxt_codeLivre;
    }

    public void setjTxt_codeLivre(JTextField jTxt_codeLivre) {
        this.jTxt_codeLivre = jTxt_codeLivre;
    }

    public JTextField getjTxt_date_remise() {
        return jTxt_date_remise;
    }

    public void setjTxt_date_remise(JTextField jTxt_date_remise) {
        this.jTxt_date_remise = jTxt_date_remise;
    }

    public JTextField getjTxt_matricule() {
        return jTxt_matricule;
    }

    public void setjTxt_matricule(JTextField jTxt_matricule) {
        this.jTxt_matricule = jTxt_matricule;
    }

    public JTextField getjTxt_nb() {
        return jTxt_nb;
    }

    public void setjTxt_nb(JTextField jTxt_nb) {
        this.jTxt_nb = jTxt_nb;
    }

  
  

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTxt_nb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxt_date_remise = new javax.swing.JTextField();
        jTxt_codeLivre = new javax.swing.JTextField();
        jTxt_matricule = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Matricule_Abonné :");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 258));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTxt_nb.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Code_livre :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Date de Remise :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Nombre de livre :");

        jTxt_date_remise.setEnabled(false);
        jTxt_date_remise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_date_remiseActionPerformed(evt);
            }
        });

        jTxt_matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_matriculeActionPerformed(evt);
            }
        });

        jButton1.setText("Valider remise");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jTxt_nb)
                            .addComponent(jTxt_date_remise, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jTxt_codeLivre)
                            .addComponent(jTxt_matricule))
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_codeLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_date_remise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTxt_nb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_matriculeActionPerformed

    private void jTxt_date_remiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_date_remiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_date_remiseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String date_ret = jTxt_date_remise.getText();
        String id_item = jTxt_codeLivre.getText();
        String matricule = jTxt_matricule.getText();
        String nb = jTxt_nb.getText();
        nb = "0";
        int vnb = Integer.valueOf(nb);
        int id_trqnsaction = 0;
        try {
            //String strDateMysql = GestionDates.chaineDateFRversEN(date_em);
            //String strDateMysql1 = GestionDates.chaineDateFRversEN(date_ret);
            Date dtDate = new Date();
            dtDate = GestionDates.dateJavaEnDateSQL(dtDate);
            Date dtDate1 = new Date();
            dtDate1 = GestionDates.dateJavaEnDateSQL(dtDate1);
            Transaction l_Transaction = new Transaction(dtDate, dtDate1, id_item, matricule, id_trqnsaction, vnb);
            boolean breation = false;
            breation = l_Transaction.lireRecupCRUD1(matricule, id_item);
            if (!matricule.equals("") && !id_item.equals("") && breation == true) {
                // Sauvegarde dans la BD
                boolean bCreation = false;
                try {
                    bCreation = l_Transaction.creerCRUD1(matricule, id_item);
                } catch (SQLException ex) {
                    Logger.getLogger(EmpruntArticles.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (bCreation) {
               
               
              
            }   
           
           
            jTxt_matricule.setText("");
           
            jTxt_nb.setText("");
            jTxt_codeLivre.setText("");                   
            dtDate = new Date();
            jTxt_date_remise.setText(GestionDates.dateEnChaineFR(dtDate));

        }else {
            JOptionPane.showMessageDialog(null, "La saisie du matricule" + " est obligatoire", "Vérifier votre saisie", JOptionPane.ERROR_MESSAGE );
        }
 
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "La saisie du matricule");   
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemisesEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemisesEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemisesEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemisesEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemisesEmprunt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxt_codeLivre;
    private javax.swing.JTextField jTxt_date_remise;
    private javax.swing.JTextField jTxt_matricule;
    private javax.swing.JTextField jTxt_nb;
    // End of variables declaration//GEN-END:variables

  
}
